import { Router, type Request } from 'express'
import mongoose from 'mongoose'
import { z } from 'zod'
import { authenticate, authorize } from '../middleware/auth.js'
import { AuditLog, Category, Notification, Order, PlatformSettings, Product, Report, SellerProfile } from '../models/Marketplace.js'
import { User } from '../models/User.js'
import { ContactMessage } from '../models/Communications.js'
import { AppError, asyncHandler } from '../utils/errors.js'

export const adminRouter = Router()
adminRouter.use(authenticate, authorize('ADMIN'))
const pageSchema = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20), q: z.string().optional() })
const paged = async (model: mongoose.Model<never>, filter: mongoose.FilterQuery<never>, page: number, limit: number, sort: Record<string, 1 | -1> = { createdAt: -1 }) => {
  const [data, total] = await Promise.all([model.find(filter).sort(sort).skip((page - 1) * limit).limit(limit).lean(), model.countDocuments(filter)])
  return { data, pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } }
}
const audit = (req: Request, action: string, entityType: string, entityId: string, metadata?: unknown) => AuditLog.create({ actorId: req.user!.id, actorRole: 'ADMIN', action, entityType, entityId, metadata, ipAddress: req.ip })
const sendPage = (res: import('express').Response, message: string, result: { data: unknown[]; pagination: unknown }) => res.json({ success: true, message, ...result })

adminRouter.get('/overview', asyncHandler(async (_req, res) => {
  const [buyers, sellers, pendingSellers, products, orders, reports, revenue] = await Promise.all([
    User.countDocuments({ role: 'BUYER' }), User.countDocuments({ role: 'SELLER' }), SellerProfile.countDocuments({ status: 'PENDING' }),
    Product.countDocuments({ status: 'PUBLISHED' }), Order.countDocuments(), Report.countDocuments({ status: { $in: ['OPEN','UNDER_REVIEW'] } }),
    Order.aggregate([{ $match: { status: { $nin: ['CANCELLED','REFUNDED'] } } }, { $group: { _id: null, total: { $sum: '$total' } } }]),
  ])
  res.json({ success: true, message: 'Admin overview loaded', data: { buyers, sellers, pendingSellers, products, orders, openReports: reports, revenue: revenue[0]?.total ?? 0 } })
}))
adminRouter.get('/users', asyncHandler(async (req, res) => { const { page, limit, q } = pageSchema.parse(req.query); const filter: mongoose.FilterQuery<typeof User> = {}; if (q) filter.$or = [{ firstName: new RegExp(q, 'i') }, { lastName: new RegExp(q, 'i') }, { email: new RegExp(q, 'i') }, { phone: new RegExp(q, 'i') }]; if (['BUYER','SELLER','ADMIN'].includes(String(req.query.role))) filter.role = String(req.query.role); if (['ACTIVE','SUSPENDED','DEACTIVATED'].includes(String(req.query.status))) filter.status = String(req.query.status); const result = await paged(User as unknown as mongoose.Model<never>, filter as mongoose.FilterQuery<never>, page, limit); sendPage(res, 'Users loaded', { ...result, data: result.data.map((u: Record<string, unknown>) => { delete u.passwordHash; return u }) }) }))
adminRouter.patch('/users/:id/status', asyncHandler(async (req, res) => { const status = z.enum(['ACTIVE','SUSPENDED','DEACTIVATED']).parse(req.body.status); const user = await User.findById(req.params.id); if (!user) throw new AppError('User not found', 404); if (user.role === 'ADMIN') throw new AppError('The platform admin account cannot be changed here', 403); user.status = status; await user.save(); await audit(req, `ADMIN_${status}_USER`, 'User', user.id, { status }); res.json({ success: true, message: 'User status updated', data: { id: user.id, status } }) }))
adminRouter.get('/sellers', asyncHandler(async (req, res) => { const { page, limit, q } = pageSchema.parse(req.query); const filter: mongoose.FilterQuery<typeof SellerProfile> = {}; if (req.query.status && ['PENDING','APPROVED','SUSPENDED','REJECTED'].includes(String(req.query.status))) filter.status = String(req.query.status); if (q) filter.$or = [{ shopName: new RegExp(q, 'i') }, { city: new RegExp(q, 'i') }]; const [data, total] = await Promise.all([SellerProfile.find(filter).populate('userId','firstName lastName email phone status').sort({ createdAt: -1 }).skip((page-1)*limit).limit(limit).lean(), SellerProfile.countDocuments(filter)]); sendPage(res, 'Sellers loaded', { data, pagination: { page, limit, total, totalPages: Math.ceil(total/limit) } }) }))
adminRouter.patch('/sellers/:id/status', asyncHandler(async (req, res) => { const status = z.enum(['APPROVED','REJECTED','SUSPENDED','PENDING']).parse(req.body.status); const profile = await SellerProfile.findById(req.params.id); if (!profile) throw new AppError('Seller not found', 404); profile.status = status; if (typeof req.body.reason === 'string') profile.moderationReason = req.body.reason.slice(0,500); await profile.save(); await Notification.create({userId:profile.userId,type:'SELLER_STATUS',title:'Shop status updated',message:`Your Kitty shop was ${status.toLowerCase()}.`,entityId:profile._id}); if (status === 'SUSPENDED') await User.findByIdAndUpdate(profile.userId, { status: 'SUSPENDED' }); if (status === 'APPROVED' || status === 'PENDING') await User.findByIdAndUpdate(profile.userId, { status: 'ACTIVE' }); await audit(req, `ADMIN_${status}_SELLER`, 'SellerProfile', profile.id, { status, reason: profile.moderationReason }); res.json({ success: true, message: `Seller ${status.toLowerCase()}`, data: profile }) }))
adminRouter.get('/products', asyncHandler(async (req, res) => { const { page, limit, q } = pageSchema.parse(req.query); const filter: mongoose.FilterQuery<typeof Product> = {}; if (req.query.status && ['DRAFT','PUBLISHED','OUT_OF_STOCK','SUSPENDED','ARCHIVED'].includes(String(req.query.status))) filter.status = String(req.query.status); if (q) filter.$or = [{ name: new RegExp(q, 'i') }, { brand: new RegExp(q, 'i') }, { sku: new RegExp(q, 'i') }]; const [data,total] = await Promise.all([Product.find(filter).populate('sellerId','firstName lastName email').populate('categoryId','name').sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Product.countDocuments(filter)]); sendPage(res,'Products loaded',{data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}}) }))
adminRouter.patch('/products/:id/moderation', asyncHandler(async (req,res)=>{ const status=z.enum(['PUBLISHED','SUSPENDED','ARCHIVED']).parse(req.body.status); const product=await Product.findByIdAndUpdate(req.params.id,{status,moderationReason:typeof req.body.reason==='string'?req.body.reason.slice(0,500):undefined},{new:true,runValidators:true}); if(!product) throw new AppError('Product not found',404); await audit(req,`ADMIN_${status}_PRODUCT`,'Product',product.id,{status,reason:product.moderationReason}); res.json({success:true,message:'Product moderation updated',data:product}) }))
adminRouter.get('/categories', asyncHandler(async (_req,res)=>{ const data=await Category.find().sort({order:1,name:1}).lean(); res.json({success:true,message:'Categories loaded',data}) }))
adminRouter.post('/categories', asyncHandler(async(req,res)=>{ const input=z.object({name:z.string().trim().min(2).max(100),slug:z.string().trim().min(2).max(120).regex(/^[a-z0-9-]+$/),description:z.string().max(1000).optional(),image:z.string().url().optional(),parentId:z.string().nullable().optional(),order:z.number().int().default(0),active:z.boolean().default(true)}).parse(req.body); if(input.parentId&&!mongoose.isValidObjectId(input.parentId)) throw new AppError('Invalid parent category',400); const category=await Category.create(input); await audit(req,'ADMIN_CREATED_CATEGORY','Category',category.id); res.status(201).json({success:true,message:'Category created',data:category}) }))
adminRouter.patch('/categories/:id', asyncHandler(async(req,res)=>{ const input=z.object({name:z.string().trim().min(2).max(100).optional(),slug:z.string().trim().min(2).max(120).regex(/^[a-z0-9-]+$/).optional(),description:z.string().max(1000).optional(),image:z.string().url().optional(),parentId:z.string().nullable().optional(),order:z.number().int().optional(),active:z.boolean().optional()}).parse(req.body); if(input.parentId&&!mongoose.isValidObjectId(input.parentId)) throw new AppError('Invalid parent category',400); const category=await Category.findByIdAndUpdate(req.params.id,input,{new:true,runValidators:true}); if(!category) throw new AppError('Category not found',404); await audit(req,'ADMIN_UPDATED_CATEGORY','Category',category.id,input); res.json({success:true,message:'Category updated',data:category}) }))
adminRouter.get('/orders', asyncHandler(async(req,res)=>{const {page,limit}=pageSchema.parse(req.query);const result=await paged(Order as unknown as mongoose.Model<never>,{} as never,page,limit);sendPage(res,'Orders loaded',result)}))
adminRouter.patch('/orders/:id/status', asyncHandler(async(req,res)=>{const status=z.enum(['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURN_REQUESTED','RETURNED','REFUNDED']).parse(req.body.status);const order=await Order.findByIdAndUpdate(req.params.id,{status},{new:true,runValidators:true});if(!order)throw new AppError('Order not found',404);await audit(req,`ADMIN_${status}_ORDER`,'Order',order.id,{status});res.json({success:true,message:'Order status updated',data:order})}))
adminRouter.get('/reports', asyncHandler(async(req,res)=>{const {page,limit}=pageSchema.parse(req.query);const filter:mongoose.FilterQuery<typeof Report>={};if(req.query.status&&['OPEN','UNDER_REVIEW','RESOLVED','DISMISSED'].includes(String(req.query.status)))filter.status=String(req.query.status);const result=await paged(Report as unknown as mongoose.Model<never>,filter as mongoose.FilterQuery<never>,page,limit);sendPage(res,'Reports loaded',result)}))
adminRouter.patch('/reports/:id', asyncHandler(async(req,res)=>{const input=z.object({status:z.enum(['UNDER_REVIEW','RESOLVED','DISMISSED']),adminNotes:z.string().max(2000).optional()}).parse(req.body);const report=await Report.findByIdAndUpdate(req.params.id,{...input,...(['RESOLVED','DISMISSED'].includes(input.status)?{resolvedAt:new Date()}:{})},{new:true,runValidators:true});if(!report)throw new AppError('Report not found',404);await audit(req,`ADMIN_${input.status}_REPORT`,'Report',report.id,input);res.json({success:true,message:'Report updated',data:report})}))
adminRouter.get('/analytics', asyncHandler(async(_req,res)=>{const [ordersByStatus,salesByDay,categoryCounts]=await Promise.all([Order.aggregate([{$group:{_id:'$status',count:{$sum:1},revenue:{$sum:'$total'}}}]),Order.aggregate([{$match:{createdAt:{$gte:new Date(Date.now()-30*86400000)}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},orders:{$sum:1},revenue:{$sum:'$total'}}},{$sort:{_id:1}}]),Product.aggregate([{$match:{status:'PUBLISHED'}},{$group:{_id:'$categoryId',products:{$sum:1},sales:{$sum:'$salesCount'}}},{$sort:{sales:-1}},{$limit:10},{$lookup:{from:'categories',localField:'_id',foreignField:'_id',as:'category'}},{$project:{products:1,sales:1,category:{$first:'$category.name'}}}])]);res.json({success:true,message:'Analytics loaded',data:{ordersByStatus,salesByDay,categoryCounts}})}))
adminRouter.get('/audit-logs', asyncHandler(async(req,res)=>{const {page,limit}=pageSchema.parse(req.query);const result=await paged(AuditLog as unknown as mongoose.Model<never>,{} as never,page,limit);sendPage(res,'Audit log loaded',result)}))
adminRouter.get('/inbox', asyncHandler(async(req,res)=>{const {page,limit,q}=pageSchema.parse(req.query);const filter:mongoose.FilterQuery<typeof ContactMessage>=q?{$or:[{name:new RegExp(q,'i')},{email:new RegExp(q,'i')},{subject:new RegExp(q,'i')},{message:new RegExp(q,'i')}]}:{};const result=await paged(ContactMessage as unknown as mongoose.Model<never>,filter as mongoose.FilterQuery<never>,page,limit);sendPage(res,'Contact messages loaded',result)}))
adminRouter.patch('/inbox/:id', asyncHandler(async(req,res)=>{const status=z.enum(['READ','RESOLVED']).parse(req.body.status);const message=await ContactMessage.findByIdAndUpdate(req.params.id,{status},{new:true,runValidators:true});if(!message)throw new AppError('Contact message not found',404);await audit(req,`ADMIN_${status}_CONTACT_MESSAGE`,'ContactMessage',message.id,{status});res.json({success:true,message:'Contact message updated',data:message})}))
adminRouter.get('/settings', asyncHandler(async(_req,res)=>{const settings=await PlatformSettings.findOneAndUpdate({key:'platform'},{$setOnInsert:{key:'platform'}},{new:true,upsert:true,setDefaultsOnInsert:true});res.json({success:true,message:'Platform settings loaded',data:settings})}))
adminRouter.patch('/settings', asyncHandler(async(req,res)=>{const input=z.object({shopName:z.string().trim().min(2).max(100),contactEmail:z.string().email(),phone:z.string().max(30),deliveryFee:z.number().min(0).max(100000),commissionPercent:z.number().min(0).max(100)}).partial().strict().parse(req.body);const settings=await PlatformSettings.findOneAndUpdate({key:'platform'},{$set:input},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});await audit(req,'ADMIN_UPDATED_PLATFORM_SETTINGS','PlatformSettings',settings.id,input);res.json({success:true,message:'Settings saved',data:settings})}))
